parameters:
#    alfa_dev_debate_login.example.class: AlfaDev\Debate\LoginBundle\Example

services:
#    alfa_dev_debate_login.example:
#        class: %alfa_dev_debate_login.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
